apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: quizzopia
build:
  local:
    push: false
  artifacts:
    - image: samsagas/riddle-shield
      context: riddle-shield
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
manifests:
  rawYaml:
    - infra/k8s/*.yaml